name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint and check types
        run: |
          yarn lint
          yarn format:check
          yarn type-check
