name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate credentials
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy to firebase
        run: yarn deploy

      - name: Notify to Slack
        uses: yukin01/slack-bot-action@master
        with:
          status: ${{ job.status }}
          oauth_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channel: notice
        if: always()
