name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate credentials
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy to firebase
        run: yarn deploy

      - name: Notify to Slack
        uses: yukin01/slack-bot-action@8983e93eb4190c09195cb70d339dcc3fa1bdb7b9 # master
        with:
          status: ${{ job.status }}
          oauth_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channel: notice
        if: always()
