name: Deploy
on:
  push:
    branches:
      - master
    # https://github.community/t5/GitHub-Actions/Github-Action-not-being-triggered/m-p/30173/highlight/true#M163
    # paths:
    #   - functions
    #   - public
    #   - firebase.json
    #   - .firebaserc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: yarn --cwd ./functions --frozen-lockfile
      - run: yarn --cwd ./functions deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
