name: Lint And Build
on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: yarn --cwd ./functions --frozen-lockfile
      - run: yarn --cwd ./functions lint
      - run: yarn --cwd ./functions build
