name: Lint And Type Check
on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/cache@preview
        id: cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --cwd ./functions --frozen-lockfile

      - name: Lint and check types
        run: |
          yarn --cwd ./functions lint
          yarn --cwd ./functions type-check
